# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35fce42abdd310e1958413d0e8cb5e434ffcd497f3f0f82cb376187197d8cea34e7c0d33c68dd8acef3261fec87cc69405e182bc5f9cbe03ed0ca122c7e6ef35

test:
  secret_key_base: ed9d52174162a32bea48aac1579108e05878761e9163067e63d5019f6344cd33e1089159fc2f58ec69f2e712da7a9a75d615fa1b7e4f2532f3ee538228127c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
